# Build settings

github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
gems:
 - jekyll-coffeescript
 - jekyll-paginate
permalink: pretty
relative_permalinks: false

include: ['_providers']

sass:
  sass_dir: static/styles
  style: :compressed
