#-------------------------------
# General Settings

title: Socialite Providers
description: A Collection of Providers for Laravel Socialite

#-------------------------------
# Navigation items

menu:
- {name: About, url: '#about'}
- {name: Packages, url: '#packages'}
- {name: Contribute, url: '#contribute'}
- {name: GitHub, url: 'https://github.com/SocialiteProviders'}
- {name: Packagist, url: 'https://packagist.org/packages/socialiteproviders/'}
